#Minecraft server properties
server-port=28828
server-ip=0.0.0.0
query.port=28828
query.enabled=true
motd=\u00a7a\u00a7lLuma\u00a7r \u00a77\u00b7 \u00a7f\u043a\u043e\u0448\u043a\u043e\u0434\u0435\u0432\u043e\u0447\u043a\u0438 \u0436\u0434\u0443\u0442
online-mode=true
white-list=false
enforce-whitelist=false
max-players=10
difficulty=normal
view-distance=8
simulation-distance=6
spawn-protection=0
allow-flight=true
max-tick-time=120000
enable-status=true
pvp=true
